# ```conda env create -f environment.yml```
name: KitaevDensityMatrix
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - matplotlib
  # (if you use notebooks):
  - jupyter
  - ipykernel
